from sqlalchemy import Column, Integer, String, ForeignKey, Float, Boolean, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()

class Patient(Base):
    __tablename__ = 'patient'

    patient_id = Column(Integer, primary_key=True, nullable=False)
    patient_address = Column(String)
    patient_admitting_physician = Column(Integer)
    allergies = Column(String)
    patient_ap = Column(String)
    patient_country = Column(String)
    patient_creating_user = Column(Integer)
    patient_creationDate = Column(DateTime)
    patient_dob = Column(DateTime)
    patient_dod = Column(DateTime)
    deathIndicator = Column(String)
    patient_email = Column(String)
    patient_ethnicity = Column(String)
    patient_forename = Column(String)
    patient_fullname = Column(String)
    patient_gpEmailAddress = Column(String)
    patient_gpfax = Column(String)
    patient_gpForename = Column(String)
    patient_gpGMPCode = Column(String)
    patient_gpPCTCode = Column(String)
    patient_gpPCTName = Column(String)
    patient_gpPostcode = Column(String)
    patient_gpPracticeCode = Column(String)
    patient_gpPracticeName = Column(String)
    patient_gpSurAdd = Column(String)
    patient_gpSurname = Column(String)
    patient_gpTelNum = Column(String)
    guid = Column(String, nullable=False)
    patient_homeTelNum = Column(String)
    patient_imageUrl = Column(String)
    patient_lang = Column(String)
    patient_marStat = Column(String)
    patient_middleName = Column(String)
    patient_mobNum = Column(String)
    patient_modifiedDate = Column(DateTime)
    patient_nationality = Column(String)
    patient_nhsNum = Column(String)
    patient_nokAddress = Column(String)
    patient_nokCountry = Column(String)
    patient_nokForename = Column(String)
    patient_nokPostcode = Column(String)
    patient_nokRelationship = Column(String)
    patient_nokSurname = Column(String)
    patient_nokTelNum1 = Column(String)
    patient_nokTelNum2 = Column(String)
    patient_occupation = Column(String)
    patient_overseasVisitor = Column(String)
    patient_postcode = Column(String)
    priority = Column(Integer, nullable=False)
    patient_referrer = Column(String)
    patient_regDisabled = Column(String)
    patient_religion = Column(String)
    patient_sex = Column(String)
    patient_surname = Column(String)
    patient_title = Column(String)
    patient_workPhNum = Column(String)
    user_user_id = Column(Integer, ForeignKey('users.user_id'))
    users = relationship('Users')
