from sqlalchemy import Column, Integer, String, ForeignKey, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()

class Subject(Base):
    __tablename__ = 'subject'

    subject_id = Column(Integer, primary_key=True, nullable=False)
    address = Column(String)
    patient_admitting_physician = Column(Integer)
    allergies = Column(String)
    assessment_plan = Column(String)
    country = Column(String)
    creating_user_id = Column(Integer)
    created_date = Column(DateTime)
    birth_date = Column(DateTime)
    death_date = Column(DateTime)
    death_indicator = Column(String)
    email = Column(String)
    ethnicity = Column(String)
    forename = Column(String)
    fullname = Column(String)
    gp_email = Column(String)
    gp_fax = Column(String)
    gp_forename = Column(String)
    gp_gmp_code = Column(String)
    gp_pct_code = Column(String)
    gp_pct_name = Column(String)
    gp_postcode = Column(String)
    gp_practice_code = Column(String)
    gp_practice_name = Column(String)
    gp_address = Column(String)
    gp_surname = Column(String)
    gp_phone = Column(String)
    guid = Column(String, nullable=False)
    home_phone = Column(String)
    image_url = Column(String)
    language = Column(String)
    marital_status = Column(String)
    middle_name = Column(String)
    mobile_phone = Column(String)
    modified_date = Column(DateTime)
    nationality = Column(String)
    nhs_number = Column(String)
    nok_address = Column(String)
    nok_country = Column(String)
    nok_frename = Column(String)
    nok_postcode = Column(String)
    nok_relationship = Column(String)
    nok_surname = Column(String)
    nok_phone_1 = Column(String)
    nok_phone_2 = Column(String)
    occupation = Column(String)
    overseas_visitor = Column(String)
    postcode = Column(String)
    priority = Column(Integer, nullable=False)
    is_disabled = Column(String)
    religion = Column(String)
    sex = Column(String)
    surname = Column(String)
    title = Column(String)
    work_phone = Column(String)
    user_user_id = Column(Integer, ForeignKey('users.user_id'))
    users = relationship('Users')
